In [1]:
import numpy as np
def sample(n):
    instance = np.random.randint(2, size=(n,))
    parity = instance.sum()%2
    return instance, parity

def instance_to_tensor(instance):
    tensor = torch.zeros(len(instance),1,2)
    for i in range(len(instance)):
        bit = instance[i]
        tensor[i][0][bit] = 1
    return tensor

def label_to_tensor(label):
    tensor = torch.zeros(1,2)
    tensor[0][label] = 1
    return tensor


def fetch_x_y(n):
    instance,label = sample(n)
    x = instance_to_tensor(instance)
    y = label_to_tensor(label)
    return x,y


In [9]:
import torch.nn as nn
# import pytorch as torch
import torch


class RNN(nn.Module):
 
    def __init__(self, input_size, hidden_size, output_size, num_layer):
        super(RNN, self).__init__()
        
        self.hidden_size = hidden_size
        self.num_layer = num_layer
                
        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        self.i2o = nn.Linear(input_size + hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim = 1)
        
    def forward(self, input):
        hidden = self.hidden
        for i in range(self.num_layer):
            combined = torch.cat((input[i], hidden), 1)
            hidden = self.i2h(combined)
#             hidden = self.softmax(hidden)
        output = self.i2o(combined)
        output = self.softmax(output)
        return output
    
    def init_hidden(self):
        init = torch.zeros(1,self.hidden_size)
        init[0][0] = 1
        self.hidden = init
        return 
    

n_hidden = 4
n_length = 3
n_catagories = 2

rnn = RNN(2, n_hidden, n_catagories,n_length)

# for param in rnn.parameters():
#     print(param)
# print(rnn.parameters())
# print(2, n_hidden, n_catagories, n_length)

In [10]:
loss_func = nn.CrossEntropyLoss()
learning_rate = 0.005 
optimizer = torch.optim.SGD(rnn.parameters(), lr=learning_rate)

def train(x,y):
    rnn.zero_grad()
    rnn.init_hidden()
    output = rnn.forward(x)

    loss = loss_func(y,output)
    loss.backward()

    optimizer.step()
    return output, loss

In [12]:
import time
import math
 
n_epochs = 100000  # 训练100000次（可重复的从数据集中抽取100000姓名）
print_every = 50 #每训练5000次，打印一次
plot_every = 10  #每训练1000次，计算一次训练平均误差

 
current_loss = 0 #初始误差为0
all_losses = [] #记录平均误差
 
def time_since(since):
    #计算训练使用的时间
    now = time.time()
    s = now - since
    m = math.floor(s / 60)
    s -= m * 60
    return '%dm %ds' % (m, s)

#训练开始时间点
start = time.time()
 
for epoch in range(1, n_epochs + 1):
    # 随机的获取训练数据name和对应的language
    x,y = fetch_x_y(n_length)

    output, loss = train(x, y)
    current_loss += loss
    print(output,loss)
 
    #每训练5000次，预测一个姓名，并打印预测情况
    if epoch % print_every == 0:
        pass
#         guess, guess_i = category_from_output(output)
#         correct = '✓' if guess == category else '✗ (%s)' % category
#         print('%d %d%% (%s) %.4f %s / %s %s' % (epoch, epoch / n_epochs * 100, time_since(start), loss, name, guess, correct))
 
    # 每训练5000次，计算一个训练平均误差，方便后面可视化误差曲线图
    if epoch % plot_every == 0:
        all_losses.append(current_loss / plot_every)
        current_loss = 0

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<LogSoftmaxBackward0>) tensor(nan, grad_fn=<DivBackward1>)
tensor([[nan, nan]], grad_fn=<Lo

KeyboardInterrupt: 